descriptions = {}

descriptions["health"] = [
    "In a bustling corridor, I spot someone collapsing, gasping for breath. Swiftly dialing emergency services; panic sets in.",
    "Heart pounding, I witness a seizure unfold in the library. Urgently seek help, feeling the seconds slip away.",
    "Chaos erupts as a student falls unconscious in the cafeteria. Grabbing attention, urgently pleading for assistance.",
    "A sudden commotion - a person clutching their chest in the lecture hall. Dialing 999, urgency escalating.",
    "Stumbling upon a distressing scene - a student choking in the courtyard. Swiftly call for aid, fear gripping.",
    "Alarming sight: a fellow student collapses, unresponsive. Dialing for help, urgency heightening.",
    "Panic ensues as a health crisis unfolds in the gym. Rushing to alert authorities, time slipping away.",
    "Frantically reacting to a fainting episode during class. Dialing for medical help urgently.",
    "In the common area, a student clutches their abdomen, in evident pain. Urgently seeking assistance.",
    "Witnessing a sudden collapse near the staircase. Swiftly reaching for my phone to call for urgent help.",
    "A student exhibits signs of a severe allergic reaction in the lab. Hastily reaching out for emergency assistance.",
    "Heart in my throat as I see someone struggling to breathe in the hallway. Dialing emergency services urgently.",
    "A health emergency disrupts the quiet study area. Urgently rallying for help, concern escalating.",
    "A sudden fall, a student writhing in pain. Urgently dialing for medical assistance.",
    "Disturbing scene: a student collapses during a group project discussion. Urgently seeking help, time crucial.",
    "An unexpected health crisis in the courtyard. Racing to inform authorities, urgency intensifying.",
    "Witnessing a fellow student experiencing a sudden blackout in the computer lab. Urgently dialing for help.",
    "Startled by a student seizing near the entrance. Swiftly reaching out for help, urgency building.",
    "In the art studio, a student collapses in distress. Urgently seeking aid, concern heightening.",
    "A health-related emergency disrupts the quiet atmosphere of the study lounge. Dialing for help urgently.",
    "Spotting a student in visible pain, clutching their stomach in the lounge. Hastily seeking emergency aid.",
    "A sudden collapse in the music room. Urgently reaching for my phone, anxiety mounting.",
    "In the outdoor seating area, a student struggles to breathe. Dialing for urgent medical assistance.",
    "Witnessing a student in distress, gripping their chest. Urgently seeking help, tension rising.",
    "A health crisis interrupts a group discussion in the courtyard. Swiftly reaching out for assistance.",
    "Panic sets in as a student collapses near the water fountain. Dialing for help urgently.",
    "Disturbing sight: a student experiencing a sudden health downturn in the study hall. Urgently seeking aid.",
    "A sudden fall in the science lab, a student in need of urgent medical attention. Dialing for help swiftly.",
    "In the quiet library, a student clutches their head in pain. Urgently reaching out for medical assistance.",
    "Witnessing a health emergency near the entrance. Swiftly dialing for urgent help, concern growing.",
    "A sudden collapse disrupts the peaceful atmosphere of the outdoor seating area. Urgently seeking assistance.",
    "Distress unfolding as a student exhibits signs of respiratory distress in the cafeteria. Dialing urgently for help.",
    "In the lecture hall, a student falls to the ground, unconscious. Urgently seeking aid, panic rising.",
    "A sudden health crisis in the courtyard. Swiftly reaching for my phone to call for emergency assistance.",
    "Witnessing a student seizing near the staircase. Dialing for help urgently, urgency intensifying.",
    "A health emergency disrupts the group study session in the library. Urgently rallying for assistance.",
    "Spotting a student in visible pain, clutching their stomach in the lounge. Urgently seeking emergency aid.",
    "A sudden collapse in the music room. Dialing for urgent medical assistance.",
    "In the outdoor seating area, a student struggles to breathe. Urgently reaching for my phone, anxiety mounting.",
    "Witnessing a student in distress, gripping their chest. Urgently seeking help, tension rising.",
    "A health crisis interrupts a group discussion in the courtyard. Swiftly reaching out for assistance.",
    "Panic sets in as a student collapses near the water fountain. Dialing for help urgently.",
    "Disturbing sight: a student experiencing a sudden health downturn in the study hall. Urgently seeking aid.",
    "A sudden fall in the science lab, a student in need of urgent medical attention. Dialing for help swiftly.",
    "In the quiet library, a student clutches their head in pain. Urgently reaching out for medical assistance.",
    "Witnessing a health emergency near the entrance. Swiftly dialing for urgent help, concern growing.",
    "A sudden collapse disrupts the peaceful atmosphere of the outdoor seating area. Urgently seeking assistance.",
    "Distress unfolding as a student exhibits signs of respiratory distress in the cafeteria. Dialing urgently for help.",
    "In the lecture hall, a student falls to the ground, unconscious. Urgently seeking aid, panic rising.",
    "I find myself in the university courtyard, observing a sudden health-related emergency. A student, visibly distressed, clutches their chest and collapses near the water fountain by the library. Urgent assistance required!",
    "In the cafeteria, a fellow student appears to be choking on their lunch. They are gesturing for help, struggling to breathe. Quick intervention needed!",
    "Walking through the corridor, I witness a student experiencing a severe allergic reaction. They are frantically searching for an epinephrine auto-injector. Immediate medical attention is essential!",
    "On the sports field, a student has taken a hard fall during a game. They lie motionless, and teammates signal for help. Swift response necessary!",
    "In the lecture hall, a student faints unexpectedly. Others around are alarmed, and it's evident they need medical aid promptly.",
    "At the entrance, a student reports feeling lightheaded and dizzy. They are unable to stand steadily. Urgent attention required to prevent further complications!",
    "In the parking lot, a student has a visible injury from a bicycle accident. They are in pain and need assistance immediately.",
    "Witnessing a student having a seizure in the computer lab. It's a distressing scene, and immediate medical attention is crucial.",
    "Near the chemistry lab, a student spills a harmful substance on themselves. They cry out in pain, necessitating urgent first aid and appropriate cleanup measures.",
    "In the music room, a student collapses while playing an instrument. Others in the room are startled, and medical help is urgently needed.",
    "In the courtyard, a student is experiencing difficulty breathing, clutching their throat. Suspected choking situation – rapid intervention required!",
    "In the gym, a student injures their ankle while exercising. They are in pain and unable to walk. Immediate assistance needed.",
    "At the staircase, a student falls and hits their head. There's a visible injury, and urgent medical attention is required.",
    "In the dormitory, a student complains of severe abdominal pain. They are doubled over and need medical assistance promptly.",
    "A student in the science lab accidentally gets a chemical in their eyes. They're in distress, and immediate eye irrigation is crucial.",
    "In the hallway, a student reports sudden chest pain. They appear anxious and in need of urgent medical attention.",
    "Witnessing a student having a severe asthma attack near the courtyard. They are struggling to breathe, and immediate intervention is necessary.",
    "In the art studio, a student accidentally cuts their hand while using a tool. Bleeding is evident, and quick first aid is essential.",
    "Near the entrance, a student shows signs of heatstroke, feeling dizzy and nauseous. They require immediate cooling and medical attention.",
    "A student in the library suddenly collapses from an unknown cause. Immediate help needed to assess and address the situation.",
    "In the psychology class, a student experiences a panic attack. They are visibly distressed and need support to manage the episode.",
    "At the campus pond, a student falls in and is struggling to stay afloat. Immediate rescue efforts are necessary.",
    "In the language lab, a student accidentally ingests a foreign substance. They're in distress, and quick medical attention is vital.",
    "In the courtyard, a student has a sudden nosebleed that won't stop. They require immediate assistance and medical attention.",
    "Witnessing a student having a diabetic emergency in the cafeteria. They need insulin urgently, and medical help is paramount.",
    "In the lecture hall, a student faints during a presentation. Quick response needed to assess their condition and provide appropriate care.",
    "A student in the physics lab gets a minor burn from an experiment gone wrong. First aid is required to treat the injury.",
    "In the dormitory, a student reports feeling chest pain and tightness. Urgent medical attention is needed to assess the situation.",
    "At the sports complex, a student collapses while running. Immediate help is needed to determine the cause and provide assistance.",
    "In the courtyard, a student stumbles and falls, complaining of severe back pain. Urgent medical attention is required.",
    "In the mathematics class, a student experiences a sudden seizure. Others are alarmed, and immediate medical intervention is crucial.",
    "At the campus clinic, a student reports feeling lightheaded and weak. They need urgent assessment and medical assistance.",
    "In the chemistry lab, a student spills a corrosive substance on their hands. Immediate first aid and thorough rinsing are necessary.",
    "In the music room, a student exhibits signs of dehydration, feeling dizzy and disoriented. They need immediate hydration and rest.",
    "Near the entrance, a student collapses and appears unresponsive. Immediate medical attention is essential to assess and address the situation.",
    "In the courtyard, a student is stung by a swarm of bees and shows signs of an allergic reaction. Urgent medical help is crucial.",
    "At the campus pond, a student falls and injures their leg. They are in pain and require immediate assistance.",
    "In the engineering lab, a student accidentally inhales fumes from a chemical reaction. They appear distressed, and immediate medical attention is vital.",
    "In the psychology class, a student experiences a sudden migraine. They need a quiet space and support to manage the pain.",
    "In the cafeteria, a student complains of severe stomach pain after eating. Immediate medical attention is necessary.",
    "In the physics lab, a student collapses due to exhaustion and dehydration. They need hydration and rest immediately.",
    "Near the library, a student reports feeling a sudden and severe headache. They need assistance and a quiet space to rest.",
    "At the sports complex, a student twists their ankle during a game. They are in pain and require immediate assistance.",
    "In the courtyard, a student is bitten by an insect and exhibits signs of an allergic reaction. Urgent medical help is necessary.",
    "In the chemistry lab, a student accidentally spills a toxic substance on their clothes. Immediate removal of contaminated clothing and thorough rinsing are crucial.",
    "In the music room, a student experiences a sudden loss of hearing. They need immediate medical attention to assess the cause.",
    "Near the entrance, a student collapses and appears disoriented. Immediate medical attention is essential to determine the cause.",
    "In the courtyard, a student is involved in a minor car accident. They report neck pain, and urgent medical assessment is needed.",
    "At the campus pond, a student falls into the water and struggles to swim. Immediate rescue efforts are necessary.",
    "In the psychology class, a student faints due to a sudden drop in blood pressure. Quick response needed to provide assistance.",
    "In the cafeteria, a student accidentally ingests a food allergen. They show signs of an allergic reaction and need immediate medical attention.",
    "In the physics lab, a student gets a paper cut that starts bleeding profusely. Quick first aid is necessary to stop the bleeding.",
    "In the dormitory, a student experiences a sudden and severe asthma attack. They require immediate intervention and medical assistance.",
    "At the sports complex, a student collapses during a workout. Immediate assessment and assistance are necessary.",
    "In the courtyard, a student is stung by a wasp and exhibits signs of an allergic reaction. Urgent medical help is crucial.",
    "In the chemistry lab, a student accidentally inhales fumes from a chemical reaction. They appear distressed, and immediate medical attention is vital.",
    "In the music room, a student complains of sudden and severe chest pain. Urgent medical attention is needed to assess the situation.",
    "Near the entrance, a student falls and injures their arm. They are in pain and require immediate assistance.",
    "In the engineering lab, a student reports feeling lightheaded and dizzy. They need urgent assessment and medical assistance.",
    "In the courtyard, a student experiences a sudden and severe headache. They need assistance and a quiet space to rest.",



    "Walking through the university courtyard, I witness a student collapsing near the fountain. They clutch their chest, visibly distressed. Urgent assistance required!",
    "In the cafeteria, a student struggles to breathe after inhaling food. Frantically gesturing for help, immediate intervention needed!",
    "On the way to the library, I come across a student experiencing a sudden allergic reaction. They urgently search for an epinephrine auto-injector. Swift medical attention is crucial!",
    "During a sports event, a student takes a hard fall, lying motionless on the field. Teammates signal for help. Quick response necessary!",
    "In the lecture hall, a student faints unexpectedly, alarming those around. Immediate medical aid is evident.",
    "At the entrance, a student reports feeling lightheaded and dizzy, struggling to stand steadily. Urgent attention required to prevent further complications!",
    "In the parking lot, a student has a visible injury from a bicycle accident, in pain and needing immediate assistance.",
    "In the computer lab, a student has a seizure, creating a distressing scene. Immediate medical attention is crucial.",
    "Near the chemistry lab, a student spills a harmful substance, crying out in pain. Urgent first aid and cleanup measures required.",
    "In the music room, a student collapses while playing an instrument. Others in the room are startled; medical help is urgently needed.",
    "In the courtyard, a student experiences difficulty breathing, clutching their throat. Suspected choking situation – rapid intervention required!",
    "In the gym, a student injures their ankle during exercise, unable to walk. Immediate assistance needed.",
    "At the staircase, a student falls and hits their head. Visible injury, urgent medical attention required.",
    "In the dormitory, a student complains of severe abdominal pain, doubled over and in need of medical assistance promptly.",
    "In the science lab, a student accidentally gets a chemical in their eyes, in distress. Immediate eye irrigation is crucial.",
    "In the hallway, a student reports sudden chest pain, appearing anxious and in need of urgent medical attention.",
    "Near the courtyard, a student has a severe asthma attack, struggling to breathe. Immediate intervention necessary.",
    "In the art studio, a student accidentally cuts their hand while using a tool. Bleeding is evident, quick first aid is essential.",
    "Near the entrance, a student shows signs of heatstroke, feeling dizzy and nauseous. Immediate cooling and medical attention required.",
    "In the library, a student suddenly collapses from an unknown cause. Immediate help needed to assess and address the situation.",
    "In the psychology class, a student experiences a panic attack, visibly distressed and in need of support to manage the episode.",
    "At the campus pond, a student falls in and is struggling to stay afloat. Immediate rescue efforts are necessary.",
    "In the language lab, a student accidentally ingests a foreign substance, in distress and quick medical attention is vital.",
    "In the courtyard, a student has a sudden nosebleed that won't stop. Immediate assistance and medical attention required.",
    "Witnessing a student having a diabetic emergency in the cafeteria, needing insulin urgently and paramount medical help.",
    "In the lecture hall, a student faints during a presentation. Quick response needed to assess their condition and provide appropriate care.",
    "In the physics lab, a student gets a minor burn from an experiment gone wrong. First aid required to treat the injury.",
    "In the dormitory, a student reports feeling chest pain and tightness, needing urgent medical attention to assess the situation.",
    "At the sports complex, a student collapses while running, immediate help needed to determine the cause and provide assistance.",
    "In the courtyard, a student stumbles and falls, complaining of severe back pain. Urgent medical attention required.",
    "In the mathematics class, a student experiences a sudden seizure, alarming others. Immediate medical intervention is crucial.",
    "At the campus clinic, a student reports feeling lightheaded and weak, needing urgent assessment and medical assistance.",
    "In the chemistry lab, a student spills a corrosive substance on their hands, requiring immediate first aid and thorough rinsing.",
    "In the music room, a student exhibits signs of dehydration, feeling dizzy and disoriented. Immediate hydration and rest required.",
    "Near the entrance, a student collapses and appears unresponsive. Immediate medical attention essential to assess and address the situation.",
    "In the courtyard, a student is stung by a swarm of bees, showing signs of an allergic reaction. Urgent medical help is crucial.",
    "At the campus pond, a student falls and injures their leg, in pain and requiring immediate assistance.",
    "In the engineering lab, a student accidentally inhales fumes from a chemical reaction, appearing distressed. Immediate medical attention is vital.",
    "In the psychology class, a student experiences a sudden migraine, needing a quiet space and support to manage the pain.",
    "In the cafeteria, a student complains of severe stomach pain after eating, requiring immediate medical attention.",
    "In the physics lab, a student collapses due to exhaustion and dehydration, needing hydration and rest immediately.",
    "Near the library, a student reports feeling a sudden and severe headache, needing assistance and a quiet space to rest.",
    "At the sports complex, a student twists their ankle during a game, in pain and requiring immediate assistance.",
    "In the courtyard, a student is bitten by an insect, showing signs of an allergic reaction. Urgent medical help is crucial.",
    "In the chemistry lab, a student accidentally spills a toxic substance on their clothes. Immediate removal of contaminated clothing and thorough rinsing are crucial.",
    "In the music room, a student experiences a sudden loss of hearing, needing immediate medical attention to assess the cause.",
    "Near the entrance, a student collapses and appears disoriented. Immediate medical attention essential to determine the cause.",
    "In the courtyard, a student is involved in a minor car accident, reporting neck pain and needing urgent medical assessment.",
    "At the campus pond, a student falls into the water and struggles to swim. Immediate rescue efforts are necessary.",
    "In the psychology class, a student faints due to a sudden drop in blood pressure, needing quick response to provide assistance.",
    "In the cafeteria, a student accidentally ingests a food allergen, showing signs of an allergic reaction and needing immediate medical attention.",
    "In the physics lab, a student gets a paper cut that starts bleeding profusely. Quick first aid necessary to stop the bleeding.",
    "In the dormitory, a student experiences a sudden and severe asthma attack, requiring immediate intervention and medical assistance.",
    "At the sports complex, a student collapses during a workout, needing immediate assessment and assistance.",
    "In the courtyard, a student is stung by a wasp and exhibits signs of an allergic reaction. Urgent medical help is crucial.",
    "In the chemistry lab, a student accidentally inhales fumes from a chemical reaction, appearing distressed. Immediate medical attention is vital.",
    "In the music room, a student complains of sudden and severe chest pain, needing urgent medical attention to assess the situation.",
    "Near the entrance, a student falls and injures their arm, in pain and requiring immediate assistance.",
    "In the engineering lab, a student reports feeling lightheaded and dizzy, needing urgent assessment and medical assistance.",
    "In the courtyard, a student experiences a sudden and severe headache, needing assistance and a quiet space to rest.",
]

descriptions["fire"] = [
    "In the student lounge, a small fire breaks out in an electrical outlet. Smoke is visible, and the fire alarm has been activated. Immediate evacuation is necessary!",
    "Walking through the dormitory corridor, I notice smoke emerging from a room. A fire has started, and the resident is shouting for help. Urgent assistance and evacuation required!",
    "In the chemistry lab, a student accidentally spills a flammable substance, resulting in a small fire. They attempt to use a fire extinguisher, but it's spreading. Immediate intervention and evacuation needed!",
    "At the campus cafe, a kitchen appliance malfunctions, causing a sudden flare-up. Flames are visible, and staff members are struggling to contain it. Evacuation is crucial!",
    "In the library, an electrical fault sparks a fire in one of the study areas. Smoke fills the room, and students are rushing to exit. Quick evacuation and alerting authorities needed!",
    "In the art studio, a student's project catches fire unexpectedly. They attempt to put it out, but it intensifies. Immediate evacuation and fire department notification necessary!",
    "In the sports complex, a storage room catches fire, possibly due to faulty wiring. Smoke is spreading, and evacuation is crucial to ensure everyone's safety.",
    "Near the campus entrance, a vehicle in the parking lot is on fire. The flames are growing, and immediate evacuation of the surrounding area is essential.",
    "In the physics lab, a student mishandles an experiment, causing a small fire. They try to control it, but it's escalating. Evacuation and fire department notification required!",
    "In the courtyard, a bin catches fire, likely due to discarded cigarette butts. The flames are spreading, and urgent intervention is necessary to prevent further escalation.",
    "In the engineering lab, a malfunctioning machine causes a fire. Smoke is billowing, and students are alarmed. Immediate evacuation and notifying the fire department are essential.",
    "At the campus pond, a barbecue event goes awry, and flames engulf the cooking area. Attendees are in a panic, and quick evacuation is necessary.",
    "In the psychology class, a student's experiment results in a small fire. They attempt to extinguish it, but it's growing. Evacuation and alerting authorities needed!",
    "In the cafeteria, a cooking appliance malfunctions, leading to a fire. Staff members are trying to control it, but it's spreading. Urgent evacuation required!",
    "In the physics lab, a student's experiment with electrical equipment causes a fire. They are struggling to contain it. Immediate evacuation and fire department notification necessary!",
    "In the dormitory kitchen, a grease fire erupts on the stove. Residents are alarmed, and the fire is spreading. Quick evacuation and fire department notification essential!",
    "In the music room, faulty wiring in electronic equipment sparks a fire. It's growing, and students need to evacuate immediately. Notify the fire department!",
    "Near the entrance, a bin catches fire, likely due to discarded cigarette butts. The flames are spreading, and urgent intervention is necessary to prevent further escalation.",
    "In the chemistry lab, a student mishandles an experiment, causing a small fire. They try to control it, but it's escalating. Evacuation and fire department notification required!",
    "At the campus pond, a barbecue event goes awry, and flames engulf the cooking area. Attendees are in a panic, and quick evacuation is necessary.",
    "In the psychology class, a student's experiment results in a small fire. They attempt to extinguish it, but it's growing. Evacuation and alerting authorities needed!",
    "In the cafeteria, a cooking appliance malfunctions, leading to a fire. Staff members are trying to control it, but it's spreading. Urgent evacuation required!",
    "In the physics lab, a student's experiment with electrical equipment causes a fire. They are struggling to contain it. Immediate evacuation and fire department notification necessary!",
    "In the dormitory kitchen, a grease fire erupts on the stove. Residents are alarmed, and the fire is spreading. Quick evacuation and fire department notification essential!",
    "In the music room, faulty wiring in electronic equipment sparks a fire. It's growing, and students need to evacuate immediately. Notify the fire department!",
    "Near the entrance, a student accidentally starts a fire while attempting to light a cigarette. The flames are spreading, and urgent intervention is necessary to prevent further escalation.",
    "In the courtyard, a student's portable charger malfunctions and sparks a fire. They try to stamp it out, but it's intensifying. Immediate evacuation and fire department notification needed!",
    "In the gym, an exercise machine overheats and catches fire. Smoke is filling the room, and patrons need to evacuate quickly. Notify the fire department!",
    "In the language lab, a student's electrical experiment results in a small fire. They attempt to extinguish it, but it's escalating. Evacuation and alerting authorities necessary!",
    "At the sports complex, a malfunctioning scoreboard sparks a fire. Smoke is visible, and spectators need to evacuate immediately. Notify the fire department!",
    "In the courtyard, a student's attempt at a DIY project results in a small fire. They are struggling to control it. Immediate evacuation and fire department notification required!",
    "In the chemistry lab, a student accidentally knocks over a Bunsen burner, causing a fire. They try to contain it, but it's spreading. Evacuation and fire department notification necessary!",
    "Near the library, an electrical panel malfunctions, leading to sparks and a small fire. Immediate evacuation is necessary to ensure safety. Notify the fire department!",
    "In the psychology class, a student's science experiment leads to a small fire. They attempt to put it out, but it's intensifying. Evacuation and alerting authorities needed!",
    "In the cafeteria, a faulty microwave causes a fire. Staff members are trying to control it, but it's spreading. Urgent evacuation required!",
    "In the physics lab, a student's experiment with volatile substances causes a fire. They are struggling to contain it. Immediate evacuation and fire department notification necessary!",
    "In the dormitory, a resident's attempt at cooking goes awry, resulting in a kitchen fire. Quick evacuation and fire department notification essential!",
    "At the sports complex, a malfunctioning electronic scoreboard sparks a fire. Smoke is visible, and spectators need to evacuate immediately. Notify the fire department!",
    "In the courtyard, a student's attempt at a chemistry experiment results in a small fire. They are trying to put it out, but it's escalating. Immediate evacuation and fire department notification needed!",
    "In the music room, a faulty amplifier starts a fire. It's spreading, and students need to evacuate immediately. Notify the fire department!",
    "Near the entrance, a student accidentally sets fire to a pile of papers. The flames are spreading, and urgent intervention is necessary to prevent further escalation.",
    "In the courtyard, a student's portable charger malfunctions and sparks a fire. They try to stamp it out, but it's intensifying. Immediate evacuation and fire department notification needed!",
    "In the gym, an exercise machine overheats and catches fire. Smoke is filling the room, and patrons need to evacuate quickly. Notify the fire department!",
    "In the language lab, a student's electrical experiment results in a small fire. They attempt to extinguish it, but it's escalating. Evacuation and alerting authorities necessary!",
    "At the sports complex, a malfunctioning scoreboard sparks a fire. Smoke is visible, and spectators need to evacuate immediately. Notify the fire department!",
    "In the courtyard, a student's attempt at a DIY project results in a small fire. They are struggling to control it. Immediate evacuation and fire department notification required!",
    "In the chemistry lab, a student accidentally knocks over",
    " a Bunsen burner, causing a fire. They try to contain it, but it's spreading. Evacuation and fire department notification necessary!",
    "Near the library, an electrical panel malfunctions, leading to sparks and a small fire. Immediate evacuation is necessary to ensure safety. Notify the fire department!",
    "In the psychology class, a student's science experiment leads to a small fire. They attempt to put it out, but it's intensifying. Evacuation and alerting authorities needed!",
    "In the cafeteria, a faulty microwave causes a fire. Staff members are trying to control it, but it's spreading. Urgent evacuation required!",
    "In the physics lab, a student's experiment with volatile substances causes a fire. They are struggling to contain it. Immediate evacuation and fire department notification necessary!",
    "In the dormitory, a resident's attempt at cooking goes awry, resulting in a kitchen fire. Quick evacuation and fire department notification essential!",
    "At the sports complex, a malfunctioning electronic scoreboard sparks a fire. Smoke is visible, and spectators need to evacuate immediately. Notify the fire department!",
    "In the courtyard, a student's attempt at a chemistry experiment results in a small fire. They are trying to put it out, but it's escalating. Immediate evacuation and fire department notification needed!",
    "In the music room, a faulty amplifier starts a fire. It's spreading, and students need to evacuate immediately. Notify the fire department!",
    "Near the entrance, a student accidentally sets fire to a pile of papers. The flames are spreading, and urgent intervention is necessary to prevent further escalation.",

    "During a biology experiment, a Bunsen burner malfunctions, causing a small fire. The teacher quickly extinguishes it, but students are shaken. Alerting facilities and checking for injuries necessary.",
    "A discarded cigarette ignites dry leaves near the campus entrance, causing a small brush fire. Quick containment and extinguishing to prevent further spread is crucial.",
    "Heavy rain and strong winds cause a tree branch to fall onto a power line, sparking a fire on the ground. Immediate evacuation from the area and contacting emergency services is essential.",
    "In the computer lab, a faulty monitor overheats and starts smoking. Students evacuate the room as the fire alarm activates. Alerting facilities and ensuring everyone is safe is the top priority.",
    "During a welding demonstration in the workshop, sparks ignite some nearby sawdust, causing a small fire. The instructor quickly extinguishes it, but everyone needs to be checked for smoke inhalation.",
    "A medical waste container in the health center catches fire due to improper disposal of flammable materials. Quick evacuation and containment are necessary to prevent the spread of flames and hazardous smoke.",
    "A power surge causes a transformer to explode outside the administration building, sparking a small fire. Evacuate the area and contact emergency services immediately.",
    "During a cooking demonstration in the home economics lab, a pan of oil overheats and catches fire. The teacher extinguishes it promptly, but everyone needs to be cleared of the immediate area.",
    "A lost child wanders into a restricted area and accidentally starts a small fire with matches. Quick response and ensuring the child's safety is paramount.",
    "A paint thinner can leaks in the art storage room, creating flammable fumes. Evacuate the area and ventilate the room to prevent ignition.",
    "Heavy snow accumulates on a roof, causing a gas leak pipe to rupture. The resulting gas ignites, causing a small fire. Evacuate the building and contact emergency services immediately.",
    "A discarded firework lands on a dry field near the sports complex, sparking a small fire. Quick containment and extinguishing are necessary to prevent further spread.",
    "A delivery truck carrying gasoline crashes on campus, causing a fuel spill and a fire. Immediate evacuation and contacting emergency services are crucial.",
    "A lightning strike hits a tree near the library, causing it to split and fall onto power lines, sparking a fire. Evacuate the area and contact emergency services immediately.",
    "During a chemistry experiment, a mixture of chemicals reacts unexpectedly, causing a small explosion and fire. Immediate evacuation and containment are necessary.",
    "A faulty light bulb in the gym ignites nearby flammable decorations, causing a small fire. Evacuate the gym and extinguish the fire before it spreads.",
    "A gas leak in the cafeteria kitchen causes an oven to explode, starting a fire. Immediate evacuation and contacting emergency services are essential.",
    "A student in the machine shop accidentally ignites some oily rags with a welding torch, causing a small fire. The instructor quickly extinguishes it, but everyone needs to be checked for injuries.",
    "A laptop battery overheats in the library, causing smoke and sparks. Evacuate the area and alert facilities to handle the situation.",
    "A discarded cigarette butt ignites a wastebasket in the restroom, causing a small fire. Quick extinguishing and ventilation are necessary.",
    "During a chemistry experiment, a student accidentally mixes incompatible chemicals, causing a violent reaction and fire. Immediate evacuation and containment are crucial.",
    "A faulty electrical panel in the basement sparks a fire, spreading smoke and flames throughout the building. Evacuate immediately and contact emergency services.",
    "A delivery drone carrying flammable materials crashes on campus and catches fire. Immediate evacuation and contacting emergency services are essential.",
    "A student in the chemistry lab accidentally ignites a mixture of chemicals, causing a small fire. The instructor quickly extinguishes it, but everyone needs to be checked for injuries.",

    "A student's clothes dryer overheats in the laundry room, catching fire. Immediate evacuation and fire department notification necessary!",
   "A bonfire lit during a campus event gets out of control, spreading flames to nearby trees. Quick response and fire department assistance are essential.",
   "A car parked in the faculty parking lot catches fire due to an electrical malfunction. Evacuate the area and contact emergency services.",
   "A lightning strike during a thunderstorm hits the science building, sparking a fire on the roof. Evacuate the building and contact emergency services immediately.",
   "A gas-powered lawnmower explodes in the maintenance shed, starting a fire. Quick containment and evacuation of the area are crucial.",
   "A student's dorm room catches fire due to a faulty extension cord. Immediate evacuation and fire department notification are needed!",
   "A candle left unattended in a study room ignites nearby papers, causing a small fire. Quick extinguishing and ventilation are necessary.",
   "A cooking oil spill on a hot stove in the cafeteria kitchen causes a fire. Evacuate the kitchen and activate the fire suppression system.",
   "A chemistry student's backpack, containing reactive chemicals, catches fire in a hallway. Immediate evacuation and containment are crucial.",
   "A bird's nest built on a power line outside a classroom window catches fire, causing smoke to enter the room. Evacuate the room and contact facilities for assistance.",
   "A discarded cigarette butt ignites dry grass near the athletic fields, starting a small brush fire. Quick containment and fire department notification are essential.",
   "A faulty space heater in a faculty office starts a fire. Evacuate the building and contact emergency services immediately.",
   "A student's laptop charger overheats and sparks, igniting nearby papers in a dorm room. Quick response and extinguishing are necessary to prevent further spread.",
   "A lightning strike during a storm ignites a fuel tank near the maintenance building, causing a large fire. Immediate evacuation and contacting emergency services are critical.",
   "A small explosion occurs in a chemistry lab due to a chemical reaction gone wrong. Immediate evacuation and containment are necessary.",
   "A paint can in the art studio spontaneously combusts, starting a fire. Evacuate the studio and activate the fire suppression system.",
   "A student's experiment in a physics lab goes awry, causing a small electrical fire. Quick response and extinguishing are needed to prevent further damage.",
   "A pile of oily rags in the auto shop spontaneously combusts, starting a fire. Evacuate the shop and activate the fire suppression system.",
   "A discarded firework ignites a trash can near the student union, causing a small fire. Quick extinguishing and ventilation are necessary.",
   "A faulty electrical outlet in a classroom sparks a fire, causing smoke to fill the room. Evacuate the building and contact emergency services immediately.",
   "A student's hairdryer overheats and catches fire in a dorm bathroom. Quick response and extinguishing are necessary to prevent further damage.",
   "A small fire breaks out in the library's book stacks due to an unknown cause. Evacuate the library and contact emergency services immediately.",
   "A cooking demonstration in the culinary arts lab goes wrong, causing a grease fire. Quick response and extinguishing are needed to prevent further spread.",
   "A student's car overheats and catches fire in the parking lot. Evacuate the area and contact emergency services.",
   "A lightning strike hits a power line near the gym, causing a power surge and a small fire. Evacuate the building and contact emergency services immediately.",
   "A student's experiment in the biology lab results in a chemical spill that ignites, starting a fire. Quick response and containment are crucial.",
   "A faulty electrical panel in the student union sparks a fire, causing smoke to fill the building. Evacuate immediately and contact emergency services.",
   "A small fire breaks out in the cafeteria kitchen due to a grease spill. Evacuate the kitchen and activate the fire suppression system.",
   "A student's dorm room catches fire due to a candle left unattended. Immediate evacuation and fire department notification are needed!",
   "A lightning strike ignites a tree near the library, causing a small fire. Evacuate the area and contact emergency services immediately.",
   "A small fire breaks out in the faculty lounge due to a faulty coffee maker. Evacuate the lounge and activate the fire suppression system.",

    "A small fire erupts in the custodial closet, likely due to improperly stored cleaning solvents. Urgent evacuation and fire department notification are required.",
   "A discarded lighter in a wastebasket ignites paper scraps, producing a minor fire in a classroom. Swift containment and extinguishing are necessary.",
   "A faulty power strip overheats, leading to a small fire behind a desk in an office space. Timely evacuation and assessment of electrical hazards are paramount.",
   "A pile of rags soaked in paint thinner spontaneously combusts in the art studio's storage area. Prompt evacuation and fire suppression efforts are crucial.",
   "A student's dorm room experiences a fire caused by an unattended candle. Immediate evacuation and fire department response are needed.",
   "A vehicle parked in the campus garage catches fire, potentially due to an electrical malfunction. Swift evacuation of the garage and activation of the fire suppression system are essential.",
   "A bonfire during a school-sanctioned event grows out of control, igniting nearby vegetation. Rapid containment and fire department intervention are crucial.",
   "A neglected incense burner in a meditation room triggers a small fire. Timely extinguishing and ventilation are necessary to prevent smoke inhalation.",
   "A grease fire erupts in the kitchen of the campus grill, posing a significant risk. Immediate evacuation and fire department response are imperative.",
   "A discarded cigarette butt ignites dry brush near a hiking trail on campus property. Urgent containment and fire department notification are required to prevent a wildfire.",
   "A student's overloaded power strip sparks a fire in their dorm room, necessitating immediate evacuation and fire department response.",
   "A laser cutter malfunctions in the engineering lab, causing a small fire. Swift containment and extinguishing are crucial to prevent further damage.",
   "A lightning strike during a storm ignites a tree on the outskirts of campus, necessitating fire department intervention to contain the blaze.",
   "A faulty space heater in a faculty office triggers a small fire. Timely evacuation and fire suppression efforts are essential.",
   "A cooking mishap in a student apartment leads to a kitchen fire, requiring immediate evacuation and fire department response.",
   "A discarded firework discarded in a trash bin ignites, causing a minor fire in a restroom. Swift extinguishing and ventilation are necessary.",
   "A faulty electrical outlet in a lecture hall sparks a fire, prompting evacuation and fire department notification.",
   "A soldering iron left unattended in the electronics lab ignites nearby materials, causing a small fire. Rapid containment and extinguishing are crucial.",
   "A student's hairdryer overheats and catches fire in a dorm room bathroom, necessitating immediate evacuation and fire department response.",
   "A chemical spill in the science lab leads to a reaction that triggers a small fire. Prompt evacuation and activation of the fire suppression system are essential.",
   "A bonfire during a student gathering grows out of control, necessitating fire department intervention to prevent further spread.",
   "A discarded cigarette butt ignites a pile of leaves near a campus building, causing a small fire. Quick containment and extinguishing are necessary.",
   "A faulty power tool in the woodworking shop sparks a fire, requiring swift evacuation and fire suppression efforts.",
   "A car accident on campus results in a vehicle fire, prompting immediate evacuation of the area and fire department response.",
   "A student's experiment in the chemistry lab goes awry, causing a small explosion and fire. Urgent evacuation and activation of the fire suppression system are required.",
   "A discarded match ignites a pile of trash in a dumpster, causing a minor fire. Timely extinguishing and ventilation are necessary.",
   "A faulty appliance in the student lounge sparks a fire, necessitating evacuation and fire department notification.",

   "Smoke billows from an electrical panel in a maintenance room, signaling a fire within. Swift evacuation and fire department response are imperative.",
   "A charred odor emanates from a storage closet, hinting at a potential fire hazard. Timely investigation and appropriate action are necessary.",
   "Flames flicker within a recycling bin, likely ignited by a carelessly discarded item. Rapid containment and extinguishing are crucial to prevent further spread.",
   "A crackling sound emanates from a faculty office, drawing attention to a small fire originating from a faulty power strip. Urgent evacuation and fire suppression efforts are required.",
]

descriptions["crime"] = [
    "In the campus parking lot, I witness a student attempting to break into a car. They look suspicious, and immediate intervention is needed. Security should be alerted.",
    "Walking near the library, I notice a heated argument between two students escalating. It turns physical, and they need to be separated immediately. Notify campus security.",
    "In the dormitory, a student reports their laptop stolen from their room. They suspect someone unauthorized entered. Immediate investigation and security involvement needed.",
    "At the campus cafe, a student snatches another's bag and runs off. A theft has occurred, and security should be notified promptly.",
    "In the engineering lab, a student notices valuable equipment missing. It appears to be a case of theft. Immediate reporting and security involvement are necessary.",
    "In the courtyard, I come across a group of students engaging in a physical altercation. They need to be separated, and campus security should intervene.",
    "At the language lab, a student reports receiving threatening messages online. This cyberbullying incident requires immediate attention from campus authorities.",
    "Near the entrance, a student is loitering suspiciously, possibly attempting to gain unauthorized access. Security should be alerted to investigate.",
    "In the psychology class, a heated argument between two students turns aggressive. They need to be separated, and campus security should be called.",
    "In the cafeteria, a student's wallet is stolen from their bag while they're distracted. Immediate reporting and involvement of campus security are essential.",
    "In the physics lab, a student notices that expensive equipment has been tampered with. It appears to be an act of vandalism or sabotage. Security should be alerted.",
    "In the gym, a student reports witnessing another stealing personal belongings from the locker room. Immediate reporting and security involvement are necessary.",
    "In the courtyard, a student is harassed by another, making them feel unsafe. This case of harassment requires immediate intervention and reporting to campus authorities.",
    "Near the campus pond, a group of students is engaging in illicit drug use. Immediate intervention and reporting to campus security are essential.",
    "In the dormitory, a student reports finding graffiti on their door. It appears to be an act of vandalism, and campus security should be notified.",
    "At the sports complex, a student's sports equipment is stolen from the storage area. Immediate reporting and involvement of campus security are necessary.",
    "In the library, a student notices someone attempting to shoplift books. Security should be alerted to prevent the theft.",
    "In the courtyard, a student is harassed by another, making them feel unsafe. This case of harassment requires immediate intervention and reporting to campus authorities.",
    "Near the campus pond, a group of students is engaging in illicit drug use. Immediate intervention and reporting to campus security are essential.",
    "In the dormitory, a student reports finding graffiti on their door. It appears to be an act of vandalism, and campus security should be notified.",
    "At the sports complex, a student's sports equipment is stolen from the storage area. Immediate reporting and involvement of campus security are necessary.",
    "In the library, a student notices someone attempting to shoplift books. Security should be alerted to prevent the theft.",
    "In the language lab, a student's personal belongings are stolen while they step away. Immediate reporting and involvement of campus security are necessary.",
    "Near the entrance, a student is distributing unauthorized flyers. This could be a violation of campus rules, and security should be notified.",
    "In the chemistry lab, a student observes another attempting to tamper with experiments. Immediate reporting and involvement of campus security are essential.",
    "In the music room, a student reports the theft of their musical instrument. Immediate reporting and involvement of campus security are necessary.",
    "At the campus pond, a student is harassed by a stranger. Immediate intervention and reporting to campus security are essential.",
    "In the psychology class, a student overhears plans for an unauthorized gathering that may lead to disruptive activities. Security should be notified to prevent any potential issues.",
    "In the cafeteria, a student witnesses another attempting to steal food without paying. Security should be alerted to address the situation.",
    "In the physics lab, a student notices someone attempting to remove equipment without authorization. Immediate reporting and involvement of campus security are necessary.",
    "In the dormitory, a student reports suspicious individuals loitering in the hallway. Security should be alerted to investigate and ensure campus safety.",
    "At the sports complex, a student reports the unauthorized use of sports facilities by non-members. Immediate reporting and involvement of campus security are essential.",
    "In the courtyard, a student is harassed by a stranger. Immediate intervention and reporting to campus security are essential.",
    "In the psychology class, a student overhears plans for an unauthorized gathering that may lead to disruptive activities. Security should be notified to prevent any potential issues.",
    "In the cafeteria, a student witnesses another attempting to steal food without paying. Security should be alerted to address the situation.",
    "In the physics lab, a student notices someone attempting to remove equipment without authorization. Immediate reporting and involvement of campus security are necessary.",
    "In the dormitory, a student reports suspicious individuals loitering in the hallway. Security should be alerted to investigate and ensure campus safety.",
    "At the sports complex, a student reports the unauthorized use of sports facilities by non-members. Immediate reporting and involvement of campus security are essential.",
    "In the courtyard, a student notices someone defacing public property with graffiti. Immediate reporting and involvement of campus security are necessary.",
    "Near the library, a student witnesses a heated argument escalating. It becomes physical, and immediate intervention is necessary. Notify campus security.",
    "In the engineering lab, a student's research materials are tampered with, possibly sabotaged. Immediate reporting and involvement of campus security are essential.",
    "At the language lab, a student reports receiving threatening messages online. This cyberbullying incident requires immediate attention from campus authorities.",
    "In the psychology class, a heated argument between two students turns aggressive. They need to be separated, and campus security should be called.",
    "In the cafeteria, a student's wallet is stolen from their bag while they're distracted. Immediate reporting and involvement of campus security are essential.",
    "In the physics lab, a student notices that expensive equipment has been tampered with. It appears to be an act of vandalism or sabotage. Security should be alerted.",
    "In the gym, a student reports witnessing another stealing personal belongings from the locker room. Immediate reporting and security involvement are necessary.",
    "In the courtyard, a student is harassed by another, making them feel unsafe. This case of harassment requires immediate intervention and reporting to campus authorities.",
    "Near the campus pond, a group of students is engaging in illicit drug use. Immediate intervention and reporting to campus security are essential.",
    "In the dormitory, a student reports finding graffiti on their door. It appears to be an act of vandalism, and campus security should be notified.",
    "At the sports complex, a student's sports equipment is stolen from the storage area. Immediate reporting and involvement of campus security are necessary.",
    "In the library, a student notices someone attempting to shoplift books. Security should be alerted to prevent the theft.",
    "In the language lab, a student's personal belongings are stolen while they step away. Immediate reporting and involvement of campus security are necessary.",
    "Near the entrance, a student is distributing unauthorized flyers. This could be a violation of campus rules, and security should be notified.",
    "In the chemistry lab, a student observes another attempting to tamper with experiments. Immediate reporting and involvement of campus security are essential.",
    "In the music room, a student reports the theft of their musical instrument. Immediate reporting and involvement of campus security are necessary.",
    "At the campus pond, a student is harassed by a stranger. Immediate intervention and reporting to campus security are essential.",
    "In the psychology class, a student overhears plans for an unauthorized gathering that may lead to disruptive activities.",
    " Security should be notified to prevent any potential issues.",
    "In the cafeteria, a student witnesses another attempting to steal food without paying. Security should be alerted to address the situation.",
    "In the physics lab, a student notices someone attempting to remove equipment without authorization. Immediate reporting and involvement of campus security are necessary.",
    "In the dormitory, a student reports suspicious individuals loitering in the hallway. Security should be alerted to investigate and ensure campus safety.",
    "At the sports complex, a student reports the unauthorized use of sports facilities by non-members. Immediate reporting and involvement of campus security are essential.",
    "In the courtyard, a student is harassed by a stranger. Immediate intervention and reporting to campus security are essential.",
    "In the psychology class, a student overhears plans for an unauthorized gathering that may lead to disruptive activities. Security should be notified to prevent any potential issues.",
    "In the cafeteria, a student witnesses another attempting to steal food without paying. Security should be alerted to address the situation.",
    "In the physics lab, a student notices someone attempting to remove equipment without authorization. Immediate reporting and involvement of campus security are necessary.",
    "In the dormitory, a student reports suspicious individuals loitering in the hallway. Security should be alerted to investigate and ensure campus safety.",
    "At the sports complex, a student reports the unauthorized use of sports facilities by non-members. Immediate reporting and involvement of campus security are essential.",
    "In the courtyard, a student notices someone defacing public property with graffiti. Immediate reporting and involvement of campus security are necessary.",
    "Near the library, a student witnesses a heated argument escalating. It becomes physical, and immediate intervention is necessary. Notify campus security.",
    "In the engineering lab, a student's research materials are tampered with, possibly sabotaged. Immediate reporting and involvement of campus security are essential.",
    "At the language lab, a student reports receiving threatening messages online. This cyberbullying incident requires immediate attention from campus authorities.",
    "In the psychology class, a heated argument between two students turns aggressive. They need to be separated, and campus security should be called.",
    "In the cafeteria, a student's wallet is stolen from their bag while they're distracted. Immediate reporting and involvement of campus security are essential.",
    "In the physics lab, a student notices that expensive equipment has been tampered with. It appears to be an act of vandalism or sabotage. Security should be alerted.",
    "In the gym, a student reports witnessing another stealing personal belongings from the locker room. Immediate reporting and security involvement are necessary.",

    "While entering the gym locker room, I saw someone forcing open a locker. They're definitely not the owner, and security needs to be called!",
    "Just spotted a group of students trying to sneak into the restricted computer lab. Looks like attempted unauthorized access, notify security ASAP!",
    "Someone broke the window of the bookstore display! Possible theft in progress, immediate intervention needed!",
    "A delivery driver reports a package stolen from the campus mailroom. Security should investigate and secure the area.",
    "In the music room, a student discovered their instrument missing from its case. Potential theft, involve security and investigate quickly.",
    "Witnessing a verbal altercation outside the student union turn physical. One person seems injured, and security needs to be called immediately!",
    "A student reports being followed and harassed near the library after dark. Security escort and investigation needed.",
    "Heard loud screams coming from a dorm room. Possible domestic violence situation, notify security and emergency services right away!",
    "A student claims they were threatened with a weapon near the sports field. This is a serious threat, contact security and police immediately!",
    "Witnessed a group of students bullying and verbally abusing another student in the cafeteria. Immediate intervention and security involvement needed.",
    "Extensive graffiti found on the walls of the academic building. Property damage, notify maintenance and security.",
    "Someone set off a fire alarm in the library as a prank. Disruptive and potentially dangerous, involve security and investigate.",
    "Smashed windows and overturned trash cans in the courtyard. Vandalism in progress, contact security and facilities immediately.",
    "A student reports their car tires slashed in the campus parking lot. Act of vandalism, notify security and investigate.",
    "Witnessed someone throwing eggs at the dorm windows. Disruptive and disrespectful behavior, involve security and residence life.",
    "Strong smell of marijuana coming from a dorm room. Possible drug use, notify RA and security discreetly.",
    "Saw someone selling suspicious pills near the student center. Potential drug dealing, alert security and authorities.",
    "A student reports finding unknown white powder in a bathroom stall. Unidentified substance, notify security and facilities for proper handling.",
    "Witnessed someone entering a restricted area behind the science building. Unauthorized access, contact security and investigate.",
    "Suspicious individuals loitering around the ATM machine late at night. Potential for attempted theft, notify security and monitor closely.",
    "A student reports receiving threatening messages online. Possible cyberbullying or harassment, involve campus IT and security.",
    "Found a lost phone with personal information on the sidewalk. Turn it in to security or lost and found immediately.",
    "Witnessed a student cheating on an exam by copying another's work. Academic dishonesty, report to professor and academic integrity office.",
    "A student reports their bicycle stolen from the designated bike rack. Theft, involve security and campus police.",
    "Someone is playing loud music in the library after closing hours. Disruptive behavior, notify security and remind them of policies.",

    "A student's backpack, containing their wallet and keys, was stolen from the study lounge. Security should be alerted and cameras checked.",
   "Someone broke into the vending machine in the student union and stole cash and snacks. Notify maintenance and security for repairs and investigation.",
   "A faculty member reports their research data stolen from their office computer. Potential security breach, involve IT and campus police for investigation.",
   "The art studio has been burglarized, and several valuable paintings are missing. Urgent action needed, contact security and authorities immediately!",
   "A student's car was vandalized and their radio stolen from the parking garage. Security should be notified and the area patrolled.",
   "A student was assaulted while walking alone on a dimly lit path near the dorms. Security should increase patrols and provide escorts after dark.",
   "An argument between roommates escalated into physical violence. Urgent intervention needed, contact RA and security immediately.",
   "A student reports receiving inappropriate and threatening messages from a classmate. Potential stalking situation, involve campus security and Title IX office.",
   "A group of students were harassed and verbally abused due to their race/ethnicity/religion/sexual orientation. Hate crime investigation needed, involve campus police and diversity office.",
   "A faculty member was assaulted by an angry student during office hours. Security and campus police should be alerted immediately.",
   "The campus website was hacked and defaced with offensive content. Cybercrime incident, involve IT and security for investigation.",
   "Someone tampered with the fire extinguishers in the dorm hallways, rendering them unusable. This is a serious safety hazard, notify maintenance and security immediately.",
   "A student's car was keyed with a derogatory message on the side. Act of vandalism and potential hate crime, involve security and campus police.",
   "The statue in the quad was vandalized with paint and graffiti. Property damage, contact facilities and security for cleanup and investigation.",
   "A group of students are setting off fireworks in the parking lot, creating a disturbance and potential fire hazard. Security should intervene and confiscate the fireworks.",
   "A student is acting erratically and seems to be under the influence of drugs. Possible overdose, call for medical assistance and notify security.",
   "A backpack containing drug paraphernalia was found in a bathroom stall. Security should investigate and dispose of the items safely.",

   "Multiple laptops were stolen from the library during a busy study session. Security should review camera footage and increase patrols.",
   "A student's phone was pickpocketed while they were distracted in a crowded cafeteria. Notify security and advise students to be vigilant.",
   "A delivery truck was robbed while making a drop-off at the campus bookstore. Emergency services and campus police should be contacted immediately.",
   "The financial aid office reports a break-in and theft of student records. Urgent action needed to protect sensitive data, involve IT and authorities.",
   "A student's dorm room was burglarized while they were away for the weekend. Security should investigate and check for signs of forced entry.",
   "A student was groped by a stranger while walking to their car in the parking lot. Security should increase patrols and provide escorts.",
   "A fight broke out at a campus party, resulting in injuries and property damage. Security and campus police should intervene and investigate.",
   "A student reports being sexually assaulted by another student at a fraternity house. Immediate action needed, involve Title IX office and authorities.",
   "A professor received threatening emails from a student who was upset about their grade. Notify campus security and mental health services for assessment.",
   "A group of students were verbally attacked and threatened based on their political beliefs. Hate crime investigation needed, involve diversity office and authorities.",
   "Windows were smashed and lights broken in the science lab, disrupting research activities. Urgent repairs needed, contact facilities and security.",
   "A student's art project was intentionally destroyed in the studio. Act of vandalism, investigate and provide support to the affected student.",
   "The campus pool was vandalized with soap and dye, rendering it unusable. Security should review camera footage and identify those responsible.",
   "Someone set off multiple fire alarms in the dorms, causing panic and evacuation. Disruptive and potentially dangerous behavior, involve authorities.",
   "A group of students are skateboarding and damaging property in the academic building. Security should intervene and enforce campus rules.",
   "A student is selling prescription drugs illegally on campus. Security should investigate and involve campus police and health services.",
   "A student is found unconscious in their dorm room with drug paraphernalia nearby. Possible overdose, call for medical assistance and notify authorities.",
   "A suspicious person is lingering around the playground, observing children. Potential predator, notify security and authorities immediately.",
   "A student reports receiving a text message offering drugs for sale. Security should investigate and alert campus police.",
   "A faculty member notices a student with a concealed weapon on campus. Urgent threat, notify security and evacuate the area immediately.","A student's identity was stolen and used to make fraudulent purchases online. Financial crime, involve IT and campus police for investigation.",
   "A student forged a professor's signature on a grade change form. Academic dishonesty, involve academic integrity office and disciplinary board.",
   "A student is caught plagiarizing a research paper. Academic misconduct, report to professor and academic integrity office for consequences.",
   "A student is found in possession of a fake ID to purchase alcohol. Security should confiscate the ID and involve campus police.",
   "A student is cyberbullying another student through social media. Harassment and potential violation of student code of conduct, involve student affairs and campus police.",
]
